local L = LibStub("AceLocale-3.0"):NewLocale("AIA", "enUS", true)

L[" calendar invite has been ignored by AIA due to your filters."] = true
L[" calendar invite."] = true
L[" calendar invites have been ignored by AIA due to your filters."] = true
L[" calendar invites."] = true
L["Accept Invites Automatically"] = true
L["Accepted "] = true
L["Accepts calendar invites where you haven't replied."] = true
L["AIA will only notify when finished if there were any invites to accept."] = true
L["Cannot configure while in combat."] = true
L["Check Again"] = true
L["Checking again!"] = true
L["Declined"] = true
L["Disable After Running"] = true
L["Do Nothing"] = true
L["Dungeon"] = true
L["Even if the minimap button is disabled, AIA still provides an LDB plugin if you want it to be displayed with addons such as StatBlockCore or TitanPanel."] = true
L["Filter by event creator/inviter name:"] = true
L["Filter by event title:"] = true
L["Filter by event type:"] = true
L["Filter by status:"] = true
L["Filtering"] = true
L["Hide Minimap Icon"] = true
L["If left unchecked, AIA will continue to scan and accept any new calendar events while you are playing."] = true
L["invite accepted this session"] = true
L["Invited"] = true
L["invites accepted this session"] = true
L["Leave blank to allow all."] = true
L["Left Click functionality"] = true
L["Lock Minimap Icon"] = true
L["Makes AIA Check if there is anything to accept now."] = true
L["Meeting"] = true
L["Middle Click functionality"] = true
L["Minimap"] = true
L["Mouse Button Interaction"] = true
L["No more invites to accept. Shutting down."] = true
L["No new invites accepted this session"] = true
L["Not Signed Up"] = true
L["Notifications"] = true
L["Notify only accepted invites"] = true
L["Notify when disabling"] = true
L["Notify when finished"] = true
L["Only accept event invites if the title of the event matches this."] = true
L["Only accept event invites if they were sent by this player."] = true
L["Only Accept events of these types:"] = true
L["Only accept invites if the event type matches this."] = true
L["Only accept invites sent by:"] = true
L["Only accept invites with title:"] = true
L["Only sign up to events created by:"] = true
L["Only sign up to events if the title of the event matches this."] = true
L["Only sign up to events if they were created by this player."] = true
L["Only sign up to events with title:"] = true
L["Open Calendar"] = true
L["Open Configuration Panel"] = true
L["Open Options"] = true
L["Options"] = true
L["Other"] = true
L["Override Declined status. Accepts calender invites where you have replied as declined."] = true
L["Override Tentative status. Accepts calender invites where you have replied as tentative."] = true
L["Pending invite"] = true
L["Pending invites"] = true
L["PvP"] = true
L["Raid"] = true
L["Right Click functionality"] = true
L["Sets AIA to disable itself when it has accepted all the invites it is allowed to."] = true
L["Sets if AIA should send a message to the chat window when it has finished."] = true
L["Sets if AIA should send a message to the chat window when it is disabled."] = true
L["Sets if AIA will send a message to the chat window if it ignores an event that does not meet the settings below. As a notification that you have unanswered events to deal with yourself."] = true
L["Show Minimap Icon"] = true
L["Sign Up to guild or community events that you are not signed up to or have not been specifically invited to."] = true
L["Tentative"] = true
L["Warn about ignored events"] = true
L["You can enter multiple events by separating each one with a comma."] = true
L["You can enter multiple names by separating each one with a comma."] = true
